spring.application.name=mystreet-backend
server.port=8080
spring.profiles.active=dev
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
springdoc.swagger-ui.path=/swagger-ui.html
app.jwt.secret=MyStreetCapstoneJwtSecretKeyForJava21SpringBootJwtToken12345
app.jwt.expiration-ms=86400000
